#Python For Data Analysis Code

In [1]:
import numpy as np

In [2]:
arr = np.arange(1000000)

In [3]:
list = list(range(1000000))

In [6]:
%time for _ in range(10): myarr = arr * 2

Wall time: 51.9 ms


In [7]:
%time for _ in range(10): mylist =[x * 2 for x in list]

Wall time: 1.68 s


In [8]:
data = np.random.randn(2,3)

In [9]:
data

array([[-0.96407617, -1.27669667,  0.73288155],
       [-0.01313963,  1.2126664 , -1.36959014]])

In [10]:
data + 10

array([[ 9.03592383,  8.72330333, 10.73288155],
       [ 9.98686037, 11.2126664 ,  8.63040986]])

In [11]:
data + data

array([[-1.92815235, -2.55339334,  1.4657631 ],
       [-0.02627927,  2.42533279, -2.73918027]])

In [12]:
data.shape

(2, 3)