In [5]:
import numpy as np
import pandas as pd

In [4]:
arr3d =np.arange(50).reshape(5,5,2)
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [8]:
arr3d =np.arange(50).reshape(2,5,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [6]:
arr3d[1,2,3]

38

In [7]:
arr3d[0,3,4]

19

In [16]:
arr3d[1,2:,1:3]

array([[36, 37],
       [41, 42],
       [46, 47]])

In [12]:
arr3d[0,2:,4:]

array([[14],
       [19],
       [24]])

In [14]:
arr3d[0,2:4,4]

array([14, 19])

In [15]:
arr3d[0:1,2:,4:]

array([[[14],
        [19],
        [24]]])

In [17]:
arr3d[0:1,2:,4]

array([[14, 19, 24]])

In [20]:
arr3d[0:,0:,0:1]

array([[[ 0],
        [ 5],
        [10],
        [15],
        [20]],

       [[25],
        [30],
        [35],
        [40],
        [45]]])

In [27]:
obj = pd.Series([10,11,12,13])

In [28]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [29]:
obj.values

array([10, 11, 12, 13], dtype=int64)

In [31]:
obj1 = pd.Series([13,25,56,85],index = ['a','b','c','d'])
obj1

a    13
b    25
c    56
d    85
dtype: int64

In [33]:
del obj1['c']

In [34]:
obj1

a    13
b    25
d    85
dtype: int64

In [ ]:
obj1['c'] = 100

In [32]:
obj1

a    13
b    25
c    56
d    85
dtype: int64

In [ ]:
index=[1,2,3,4,5] 

In [36]:
obj2 = pd.Series(['apple',"orange","mango","red","green","blue"])
obj2

0     apple
1    orange
2     mango
3       red
4     green
5      blue
dtype: object

In [37]:
obj2[4]

'green'

In [39]:
obj2[[3,5,1]]

3       red
5      blue
1    orange
dtype: object

In [40]:
obj2=="Orange"

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [44]:
obj2[obj2=="Orange"]

Series([], dtype: object)

In [43]:
obj2 * 2

0      appleapple
1    orangeorange
2      mangomango
3          redred
4      greengreen
5        blueblue
dtype: object

In [45]:
print("apple"*5)

appleappleappleappleapple


In [53]:
s1 = pd.Series([100,200,300,400,500],index=['H','E','L',"L","O"])

In [54]:
s1

H    100
E    200
L    300
L    400
O    500
dtype: int64

In [7]:
sdata = {'Ohio':3500,'Texas':7100,"Orego":16000,"Ullu":5000}

In [49]:
s2 = pd.Series(sdata)

In [50]:
s2

Ohio      3500
Texas     7100
Orego    16000
Ullu      5000
dtype: int64

In [55]:
'6h' in s1

False

In [56]:
'4h' in s1

False

In [1]:
states = ['california','ohio','origin','texas']

In [8]:
s2= pd.Series(sdata,index=states)

In [61]:
s2

california   NaN
ohio         NaN
origin       NaN
texas        NaN
dtype: float64

In [9]:
s2[pd.isnull]

california   NaN
ohio         NaN
origin       NaN
texas        NaN
dtype: float64