In [100]:
import numpy as np

In [56]:
_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [3]:
_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [5]:
threeD = np.arange(64).reshape(4,4,4)

In [6]:
threeD

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [10]:
threeD = np.arange(30).reshape(3,5,2)

In [11]:
threeD

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [13]:
a = [2,4,6,8,10]

In [14]:
b = []
for num in a:
    b.append(2*num)
b

[4, 8, 12, 16, 20]

In [15]:
a = np.array([1,2,3,4,5,6])

In [16]:
type(a)

numpy.ndarray

In [17]:
2*a

array([ 2,  4,  6,  8, 10, 12])

In [27]:
data = np.random.randn(2,3)
data

array([[-2.83374775, -0.54466423,  0.54670998],
       [-0.3379051 , -2.13083428,  0.39636147]])

In [29]:
data1 =np.random.randn(2,3)
data

array([[-2.83374775, -0.54466423,  0.54670998],
       [-0.3379051 , -2.13083428,  0.39636147]])

In [30]:
data1 = np.arange(10)

In [31]:
data1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
data1.ndim

1

In [35]:
data1.ndim

1

In [36]:
data1.ndim

1

In [37]:
data.shape

(2, 3)

In [38]:
b= np.array([[100]])

In [39]:
b.ndim

2

In [40]:
b.shape

(1, 1)

In [41]:
data * 10

array([[-28.33747752,  -5.44664234,   5.46709985],
       [ -3.37905096, -21.3083428 ,   3.96361472]])

In [42]:
data + data

array([[-5.6674955 , -1.08932847,  1.09341997],
       [-0.67581019, -4.26166856,  0.79272294]])

In [44]:
m1 = np.arange(12).reshape(4,3)
m2 = np.array([[1,2,3],[4,5,6],[7,8,9],[4,3,2]])

In [45]:
m1.shape == m2.shape

True

In [46]:
m1+m2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [13, 13, 13]])

In [47]:
m1/m2

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889],
       [2.25      , 3.33333333, 5.5       ]])

In [48]:
m1-m2

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [ 5,  7,  9]])

In [49]:
m1*m2

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72],
       [36, 30, 22]])

In [50]:
m1.shape

(4, 3)

In [51]:
m2.shape

(4, 3)

In [58]:
m3 = np.arange(12).reshape(3,4)

In [53]:
m3.shape

(4, 3)

In [59]:
print(m1.shape)
print(m3.shape)
m1@m3

(4, 3)
(3, 4)


array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [60]:
np.dot(m1,m3)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [61]:
m1.dot(m3)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [64]:
a =np.array([33,44,66],dtype="float32")

In [65]:
a

array([33., 44., 66.], dtype=float32)

In [ ]:
b= np.array

In [66]:
np.ones((10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.empty(6)

array([2.12199579e-314, 6.36598737e-314, 1.06099790e-313, 1.48539705e-313,
       1.90979621e-313, 2.33419537e-313])

In [ ]:
# pixels range 0 to 255.
#if all pixels 0 ,white color
#if all pixels 256 ,black color
#empty function use for hot coding

In [69]:
np.ones((3,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
np.full

In [76]:
jaaa=np.ones_likes(baaaa)
jaaa

AttributeError: module 'numpy' has no attribute 'ones_likes'

In [77]:
alist = [1,2,3,4,5,6,7,8]

In [72]:
alist[4]

5

In [74]:
type(alist)

list

In [75]:
type(alist[4])

int

In [79]:
type(alist[2:4])

list

In [80]:
td = np.arange(36).reshape(6,6)

In [81]:
td

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [82]:
td[2,3]

15

In [83]:
td[2][3]

15

In [85]:
#td[r,c]
#td[--,--]
td[2:5,2:4]

array([[14, 15],
       [20, 21],
       [26, 27]])

# boolean indexing

In [66]:
names = np.array(['bob','joe','will','bob','will','joe','joe'])

In [74]:
data = np.random.randn(7,4)

In [75]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [39]:
data

array([[0.53766902, 0.73013229, 0.04223859, 0.58621957],
       [0.67230798, 0.93329342, 0.61258212, 0.02973245],
       [0.94634409, 0.83747245, 0.20255668, 0.73501908],
       [0.11870615, 0.10719281, 0.50934739, 0.65357047],
       [0.03913805, 0.63836514, 0.18518944, 0.07014302],
       [0.94103466, 0.59374483, 0.69032801, 0.15502456],
       [0.37272547, 0.66689086, 0.03453306, 0.66167565]])

In [76]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [41]:
data[names == 'bob']

array([[0.53766902, 0.73013229, 0.04223859, 0.58621957],
       [0.11870615, 0.10719281, 0.50934739, 0.65357047]])

In [42]:
data[names != 'bob']

array([[0.67230798, 0.93329342, 0.61258212, 0.02973245],
       [0.94634409, 0.83747245, 0.20255668, 0.73501908],
       [0.03913805, 0.63836514, 0.18518944, 0.07014302],
       [0.94103466, 0.59374483, 0.69032801, 0.15502456],
       [0.37272547, 0.66689086, 0.03453306, 0.66167565]])

In [43]:
data[names == 'bob',2:]

array([[0.04223859, 0.58621957],
       [0.50934739, 0.65357047]])

In [44]:
data

array([[0.53766902, 0.73013229, 0.04223859, 0.58621957],
       [0.67230798, 0.93329342, 0.61258212, 0.02973245],
       [0.94634409, 0.83747245, 0.20255668, 0.73501908],
       [0.11870615, 0.10719281, 0.50934739, 0.65357047],
       [0.03913805, 0.63836514, 0.18518944, 0.07014302],
       [0.94103466, 0.59374483, 0.69032801, 0.15502456],
       [0.37272547, 0.66689086, 0.03453306, 0.66167565]])

In [45]:
data[names == 'bob',1:3]

array([[0.73013229, 0.04223859],
       [0.10719281, 0.50934739]])

In [58]:
mask = (names == 'bob') | (names == 'will')

In [70]:
data = np.random.randn(7,4)
data

array([[ 0.25396931,  0.21944259,  1.87572343, -0.85986554],
       [ 0.17550946, -2.5070894 , -1.04420742,  0.80182458],
       [ 1.09817393, -1.22529656,  0.43728803,  0.00635427],
       [ 1.40322862, -0.81585375,  0.08224885, -0.30313676],
       [-0.0493276 , -0.43822875,  1.01981243, -0.66580022],
       [-3.42906955,  0.59241614, -0.54562788, -1.55368375],
       [ 1.09667195,  0.12882836, -0.94315522,  0.7018952 ]])

In [59]:
data[mask]

array([[0.53766902, 0.73013229, 0.04223859, 0.58621957],
       [0.94634409, 0.83747245, 0.20255668, 0.73501908],
       [0.11870615, 0.10719281, 0.50934739, 0.65357047],
       [0.03913805, 0.63836514, 0.18518944, 0.07014302]])

In [71]:
data < 0

array([[False, False, False,  True],
       [False,  True,  True, False],
       [False,  True, False, False],
       [False,  True, False,  True],
       [ True,  True, False,  True],
       [ True, False,  True,  True],
       [False, False,  True, False]])

In [72]:
data[data < 0]

array([-0.85986554, -2.5070894 , -1.04420742, -1.22529656, -0.81585375,
       -0.30313676, -0.0493276 , -0.43822875, -0.66580022, -3.42906955,
       -0.54562788, -1.55368375, -0.94315522])

In [77]:
data[data < 0] = 0

In [78]:
data

array([[0.44500151, 0.        , 0.01310486, 1.17725739],
       [0.        , 1.39874991, 0.        , 3.45644303],
       [1.37003911, 0.4200125 , 0.37697401, 0.88047857],
       [1.74988989, 0.9788719 , 2.04680769, 0.01422406],
       [0.79237807, 0.        , 0.        , 0.71121265],
       [0.        , 0.        , 0.53352558, 0.        ],
       [0.63377172, 0.        , 0.58030894, 0.        ]])

# fancy indexing

In [90]:
arr = np.empty((8,4))

In [91]:
for i in range(8):
    arr[i] = i

In [92]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [93]:
arr[4]

array([4., 4., 4., 4.])

In [95]:
arr[4,2]

4.0

In [97]:
arr[4,:2]

array([4., 4.])

In [102]:
arr = np.arange(32).reshape(32).reshape((8,4))

In [103]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [104]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [108]:
arr[[1,5,7,2],[:,0,3,1,2]]

SyntaxError: invalid syntax (<ipython-input-108-c7220afbd218>, line 1)

In [109]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [111]:
arr= np.random.randn(7) * 5

In [112]:
arr

array([ 1.525442  ,  3.57013542, -0.7992466 , -4.65368254, -2.83566388,
       -6.0777237 ,  4.23838799])

# Advanced Array Manipulation